"""Add create attribute in Occurrence

Revision ID: 0332f2cf8f39
Revises: b3768add6b27
Create Date: 2022-08-16 00:09:27.760041

"""
import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0332f2cf8f39'
down_revision = 'b3768add6b27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occurrence', sa.Column('create', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occurrence', 'create')
    # ### end Alembic commands ###
