"""Add hero model

Revision ID: 5339c5d95438
Revises: 92a5e6a6e279
Create Date: 2022-08-14 17:38:08.942840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5339c5d95438'
down_revision = '92a5e6a6e279'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rank', sa.Enum('rankS', 'rankA', 'rankB', 'rankC', name='heroranks'), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('long', sa.Numeric(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_id'), 'hero', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_id'), table_name='hero')
    op.drop_table('hero')
    # ### end Alembic commands ###
