"""Updating Enums

Revision ID: 626c6cc43ebe
Revises: 0332f2cf8f39
Create Date: 2022-08-16 21:06:14.416954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626c6cc43ebe'
down_revision = '0332f2cf8f39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
