"""Add occurrence and attendance

Revision ID: b3768add6b27
Revises: 5339c5d95438
Create Date: 2022-08-15 02:18:43.296228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3768add6b27'
down_revision = '5339c5d95438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_name', sa.String(), nullable=False),
    sa.Column('rank', sa.Enum('god', 'dragon', 'tiger', 'wolf', name='occurrenceranks'), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('long', sa.Numeric(), nullable=False),
    sa.Column('start', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finish', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occurrence_id'), 'occurrence', ['id'], unique=False)
    op.create_table('Attendance',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrence.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'occurrence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Attendance')
    op.drop_index(op.f('ix_occurrence_id'), table_name='occurrence')
    op.drop_table('occurrence')
    # ### end Alembic commands ###
